In [ ]:
#Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 
#Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste 
#"interne" sono della stessa dimensione

In [5]:
import numpy as np
import pandas as pd
import math

In [1]:
 mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 

In [4]:
mat_array = np.array(mat)

In [6]:
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
mat_array.shape

(3, 5)

In [8]:
mat_array[0,:]

array([0, 1, 2, 3, 4])

mat_array[-2 , :]

In [9]:
mat_array[1,2]

7

In [13]:
x = math.sin(15)

In [14]:
x

0.6502878401571168

In [ ]:
#Importiamo il modulo math e proviamo a usare 
#le funzioni .sin() .cos() .factorial() e 
#la variabile .pi la riconoscete?

In [ ]:
print( *SIN di 90°, math.sin(90) *COS di 90°, math.cos(90), ( *SIN di 180°, math.sin(180) *COS di 180°, math.cos(180)

In [ ]:
#Proviamo a eseguire math.degrees(math.pi)
#Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare help(math.degrees)

In [15]:
print( *SIN di 90°, math.sin(math.pi/2) *COS di 90°, math.cos(math.pi/2), ( *SIN di 180°, math.sin(math.pi) *COS di 180°, math.cos(math.pi)

SyntaxError: invalid character '°' (U+00B0) (3386702267.py, line 1)

In [17]:
#print(math.factorial(9))

362880


In [18]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [19]:
lst = np.array(lst)

In [ ]:
#qual è stata la vendita massima mensile?

In [20]:
print(lst.max())

8150


In [ ]:
#qual è stata la vendita minima mensile?

In [22]:
print(lst.min())

1280


In [ ]:
#quali sono le vendite mensili maggiori di 4999 oggetti? 

In [24]:
filter = lst[lst > 4999]

In [25]:
print(filter)

[5500 7200 6410 8150 7100 5350]


In [ ]:
#E quante ne sono?

In [28]:
print("Quanti sono:", len(filter))


Quanti sono: 6


In [ ]:
#quali sono le vendite minori di 3000 oggetti?

In [29]:
filter_3000 = lst[lst < 3000]

In [30]:
print(filter_3000)

[2000 1280 1900 2500]


In [ ]:
#quali sono le vendite minori di 3000 oggetti?

In [32]:
print("Quanti sono:", len(filter_3000))

Quanti sono: 4


In [ ]:
# E qual'è la media?

In [ ]:
print("media al mese arrotondata a 2 cifre", round(lst.mean(),2)

In [ ]:
#Consideriamo il seguente dizionario: fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
#Consideriamo ora la seguente Series: fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
#index=range(1997, 2005)) Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997]

In [41]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}

In [44]:
 fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

In [ ]:
#Dunque qual è la differenza tra i due tipi di dato?

In [ ]:
#accesso tramite chiave x restitusce y {x,y}

In [45]:
print("tipo di valore del dizionario", type (fatturati_dict[1997]))

tipo di valore del dizionario <class 'int'>


In [46]:
print("tipo di valore del series", type (fatturati_series[1997]))

tipo di valore del series <class 'numpy.int64'>


In [47]:
print("massimo delle serie", fatturati_series.max())

massimo delle serie 25000


In [56]:
print("Between\n*", fatturati_series.between(15_000, 20_000))

Between
* 1997    False
1998     True
1999     True
2000    False
2001    False
2002     True
2003    False
2004    False
dtype: bool


In [59]:
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

In [60]:
print(stipendi)

[ 100  200  300  400  500  600  700  800  900 1000]


In [ ]:
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi:
# con un ciclo for

In [61]:
lista_stipendi = []

In [72]:
lista_stipendi_raddoppiati = []
lista_stipendi_raddoppiati_com = []

In [62]:
print(stipendi[1])

200


In [ ]:
for stipendio in stipendi:
lista_stipendi.append(stipendio*2)

In [66]:
print(lista_stipendi)

[]


In [74]:
lista_stipendi_raddoppiati_com = [ stipendio*2 for stipendio in stipendi]

In [ ]:
print("lista stipindi raddopiati", lista_stipendi_raddopiati)